//! Loaders for the tiny nanolab golden fixtures in `fixtures/tiny/`.
//!
//! Every file is generated by `python/regen_tiny.sh` (torch on CPU, fp32) or,
//! for `batch_starts.json`, by `examples/dump_batch_starts.rs` (ojas-data's
//! `BatchSampler`). The files are embedded with `include_bytes!`, so tests do
//! not depend on the working directory. Each loader validates what it can
//! without a model: dtypes, shapes, names against framework-design.md §2,
//! and the metadata it reports.

use std::path::PathBuf;

use ojas_core::OjasError;

use crate::safetensors::{SafeTensors, StDtype};
use crate::spec::{expected_params, parse_spec, ModelSpec};
use crate::{bad, field, parse_json_with, Json, JsonExt, GOLDEN_JSON};

/// Absolute path of `fixtures/tiny` (for code that needs a file, such as a
/// trainer opening `tokens.bin` through ojas-data).
pub const TINY_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/tiny");

const INIT: &[u8] = include_bytes!("../fixtures/tiny/init.safetensors");
const FORWARD: &[u8] = include_bytes!("../fixtures/tiny/forward.safetensors");
const GRADS_INIT: &[u8] = include_bytes!("../fixtures/tiny/grads_init.safetensors");
const GRADS_STEP5: &[u8] = include_bytes!("../fixtures/tiny/grads_step5.safetensors");
const TRACE_F32: &[u8] = include_bytes!("../fixtures/tiny/trace_ns5_f32.safetensors");
const TRACE_BF16: &[u8] = include_bytes!("../fixtures/tiny/trace_ns5_bf16.safetensors");
const LR_SCHEDULES: &str = include_str!("../fixtures/tiny/lr_schedules.json");
const BATCH_STARTS: &str = include_str!("../fixtures/tiny/batch_starts.json");
const TOKENS: &[u8] = include_bytes!("../fixtures/tiny/tokens.bin");

/// The torch the fixtures were generated with. A regeneration under another
/// version must update this deliberately.
pub const TORCH_VERSION: &str = "2.13.0";
pub const GOLDEN_SEED: u64 = 1337;

// ---------------------------------------------------------------------------
// tensors
// ---------------------------------------------------------------------------

/// One f32 tensor, row-major.
#[derive(Clone, Debug, PartialEq)]
pub struct HostTensor {
    pub name: String,
    pub shape: Vec<usize>,
    pub data: Vec<f32>,
}

/// Named f32 tensors with unique names.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct TensorSet {
    tensors: Vec<HostTensor>,
}

impl TensorSet {
    /// Refuses duplicate names and data whose length disagrees with the shape.
    pub fn new(tensors: Vec<HostTensor>) -> Result<Self, OjasError> {
        for (i, t) in tensors.iter().enumerate() {
            if tensors[..i].iter().any(|u| u.name == t.name) {
                return Err(bad(&format!("duplicate tensor {}", t.name)));
            }
            if crate::product(&t.shape)? != t.data.len() {
                return Err(bad(&format!(
                    "{}: data length disagrees with shape",
                    t.name
                )));
            }
        }
        Ok(Self { tensors })
    }

    pub fn get(&self, name: &str) -> Option<&HostTensor> {
        self.tensors.iter().find(|t| t.name == name)
    }

    pub fn iter(&self) -> impl Iterator<Item = &HostTensor> {
        self.tensors.iter()
    }

    pub fn names(&self) -> Vec<&str> {
        self.tensors.iter().map(|t| t.name.as_str()).collect()
    }

    pub fn len(&self) -> usize {
        self.tensors.len()
    }

    pub fn is_empty(&self) -> bool {
        self.tensors.is_empty()
    }
}

fn f32_set(st: &SafeTensors<'_>) -> Result<TensorSet, OjasError> {
    let mut out = Vec::new();
    for e in st.entries() {
        if e.dtype != StDtype::F32 {
            return Err(bad(&format!("{}: expected F32", e.name)));
        }
        out.push(HostTensor {
            name: e.name.clone(),
            shape: e.shape.clone(),
            data: st.f32s(&e.name)?,
        });
    }
    TensorSet::new(out)
}

/// The ids of one micro-batch, row-major `[batch, seq_len]`, as
/// `ojas_data::Batch` holds them.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TokenBatch {
    pub x: Vec<u32>,
    pub y: Vec<u32>,
    pub batch: usize,
    pub seq_len: usize,
}

// ---------------------------------------------------------------------------
// metadata
// ---------------------------------------------------------------------------

/// A JSON object from a fixture's metadata, with typed accessors that fail
/// loudly on a missing or mistyped key.
#[derive(Clone, Debug)]
pub struct Meta(Json);

impl Meta {
    fn parse(text: &str) -> Result<Self, OjasError> {
        let json = parse_json_with(text, GOLDEN_JSON)?;
        json.object()?;
        Ok(Self(json))
    }

    fn get(&self, key: &str) -> Result<&Json, OjasError> {
        field(self.0.object()?, key).ok_or_else(|| bad(&format!("metadata missing {key:?}")))
    }

    pub fn has(&self, key: &str) -> bool {
        self.get(key).is_ok()
    }

    pub fn str(&self, key: &str) -> Result<&str, OjasError> {
        self.get(key)?
            .text()
            .ok_or_else(|| bad(&format!("metadata {key:?} is not a string")))
    }

    pub fn num(&self, key: &str) -> Result<f64, OjasError> {
        let v = self.get(key)?.number()?;
        if v.is_finite() {
            Ok(v)
        } else {
            Err(bad(&format!("metadata {key:?} is not finite")))
        }
    }

    /// An exact non-negative integer literal. `256.0` is refused, as the
    /// model's spec reader refuses it.
    pub fn count(&self, key: &str) -> Result<usize, OjasError> {
        let n = self
            .get(key)?
            .as_u64()
            .map_err(|e| bad(&format!("metadata {key:?}: {}", e.detail())))?;
        usize::try_from(n).map_err(|_| bad(&format!("metadata {key:?} = {n} exceeds usize")))
    }

    /// An array of exact non-negative integer literals.
    pub fn counts(&self, key: &str) -> Result<Vec<u64>, OjasError> {
        self.get(key)?
            .items()?
            .iter()
            .map(|v| {
                v.as_u64()
                    .map_err(|e| bad(&format!("metadata {key:?}: {}", e.detail())))
            })
            .collect()
    }

    pub fn bool(&self, key: &str) -> Result<bool, OjasError> {
        self.get(key)?
            .flag()
            .ok_or_else(|| bad(&format!("metadata {key:?} is not a boolean")))
    }

    pub fn numbers(&self, key: &str) -> Result<Vec<f64>, OjasError> {
        self.get(key)?.numbers()
    }

    pub fn strings(&self, key: &str) -> Result<Vec<String>, OjasError> {
        self.get(key)?
            .items()?
            .iter()
            .map(|v| {
                v.text()
                    .map(str::to_string)
                    .ok_or_else(|| bad(&format!("metadata {key:?} holds a non-string")))
            })
            .collect()
    }

    pub fn object(&self, key: &str) -> Result<Meta, OjasError> {
        let v = self.get(key)?;
        v.object()?;
        Ok(Meta(v.clone()))
    }
}

/// `__metadata__["ojas.oracle"]`, or the provenance fields of a JSON fixture.
#[derive(Clone, Debug)]
pub struct Provenance {
    pub generator: String,
    pub torch: String,
    pub python: String,
    pub nanolab_head: String,
    pub meta: Meta,
}

impl Provenance {
    fn from_meta(meta: Meta) -> Result<Self, OjasError> {
        if meta.str("format")? != "ojas-oracle-fixture-v1" {
            return Err(bad("provenance format is not ojas-oracle-fixture-v1"));
        }
        if meta.str("device")? != "cpu"
            || meta.count("threads")? != 1
            || !meta.bool("deterministic")?
        {
            return Err(bad(
                "fixture was not generated on one deterministic CPU thread",
            ));
        }
        let head = meta.str("nanolab_head")?.to_string();
        if head.len() != 40 || !head.bytes().all(|b| b.is_ascii_hexdigit()) {
            return Err(bad("nanolab_head is not a git commit id"));
        }
        Ok(Self {
            generator: meta.str("generator")?.to_string(),
            torch: meta.str("torch")?.to_string(),
            python: meta.str("python")?.to_string(),
            nanolab_head: head,
            meta,
        })
    }

    fn of(st: &SafeTensors<'_>) -> Result<Self, OjasError> {
        let text = st
            .metadata("ojas.oracle")
            .ok_or_else(|| bad("missing __metadata__[\"ojas.oracle\"]"))?;
        Self::from_meta(Meta::parse(text)?)
    }

    /// The nanolab `Config` the generator ran (`config` object).
    pub fn config(&self) -> Result<Meta, OjasError> {
        self.meta.object("config")
    }

    pub fn kind(&self) -> Result<&str, OjasError> {
        self.meta.str("kind")
    }
}

/// The nanolab `Config` fields must describe `spec`.
fn check_config_matches_spec(cfg: &Meta, spec: &ModelSpec) -> Result<(), OjasError> {
    let pairs = [
        ("vocab_size", spec.vocab),
        ("d_model", spec.n_embd),
        ("n_layer", spec.n_layer),
        ("n_head", spec.n_head),
        ("n_kv_head", spec.n_kv_head),
        ("head_dim", spec.head_dim),
        ("block_size", spec.max_seq),
    ];
    for (key, want) in pairs {
        if cfg.count(key)? != want {
            return Err(bad(&format!("config {key} disagrees with the spec")));
        }
    }
    if cfg.str("dtype")? != "fp32" || cfg.bool("compile")? || cfg.str("device")? != "cpu" {
        return Err(bad("fixture config is not fp32, eager, CPU"));
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// (a) init
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
pub struct InitFixture {
    pub spec: ModelSpec,
    pub provenance: Provenance,
    pub params: TensorSet,
}

/// Parse any `model.safetensors` written by `python/export_init.py`.
///
/// Names and shapes must be exactly §2's table for the stored spec. A
/// `lm_head.weight` is accepted only when it is bit-equal to
/// `tok_emb.weight`, and is then dropped (§2 init notes).
pub fn load_init(bytes: &[u8]) -> Result<InitFixture, OjasError> {
    let st = SafeTensors::parse(bytes)?;
    let spec = parse_spec(
        st.metadata("ojas.spec")
            .ok_or_else(|| bad("missing __metadata__[\"ojas.spec\"]"))?,
    )?;
    let provenance = Provenance::of(&st)?;
    check_config_matches_spec(&provenance.config()?, &spec)?;
    let mut tensors: Vec<HostTensor> = f32_set(&st)?.tensors;
    if let Some(i) = tensors.iter().position(|t| t.name == "lm_head.weight") {
        let head = tensors.remove(i);
        let emb = tensors
            .iter()
            .find(|t| t.name == "tok_emb.weight")
            .ok_or_else(|| bad("lm_head.weight without tok_emb.weight"))?;
        let same = head.shape == emb.shape
            && head
                .data
                .iter()
                .zip(&emb.data)
                .all(|(a, b)| a.to_bits() == b.to_bits());
        if !same {
            return Err(bad("lm_head.weight is not bit-equal to tok_emb.weight"));
        }
    }
    let params = TensorSet::new(tensors)?;
    check_names_and_shapes(&params, &spec)?;
    Ok(InitFixture {
        spec,
        provenance,
        params,
    })
}

/// `params` holds exactly §2's parameters for `spec`, with §2's shapes.
pub fn check_names_and_shapes(params: &TensorSet, spec: &ModelSpec) -> Result<(), OjasError> {
    let rows = expected_params(spec);
    if params.len() != rows.len() {
        return Err(bad(&format!(
            "{} tensors, §2 lists {}",
            params.len(),
            rows.len()
        )));
    }
    for row in &rows {
        let t = params
            .get(&row.name)
            .ok_or_else(|| bad(&format!("missing §2 parameter {}", row.name)))?;
        if t.shape != row.shape {
            return Err(bad(&format!(
                "{}: shape {:?}, §2 says {:?}",
                row.name, t.shape, row.shape
            )));
        }
    }
    Ok(())
}

pub fn tiny_init() -> Result<InitFixture, OjasError> {
    load_init(INIT)
}

// ---------------------------------------------------------------------------
// (b) forward
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct LogitsChecksums {
    /// Σ logits (exact sum, `math.fsum`).
    pub sum: f64,
    /// Σ logits².
    pub sum_sq: f64,
    /// Σ logits\[i\]·((i mod 1021) + 1), i over the flat row-major logits.
    pub weighted: f64,
    pub count: usize,
}

impl LogitsChecksums {
    /// The same sums over `logits`, in f64, summed in order.
    pub fn of(logits: &[f32]) -> Self {
        let mut s = (0.0, 0.0, 0.0);
        for (i, &v) in logits.iter().enumerate() {
            let v = f64::from(v);
            s.0 += v;
            s.1 += v * v;
            s.2 += v * ((i % 1021) + 1) as f64;
        }
        Self {
            sum: s.0,
            sum_sq: s.1,
            weighted: s.2,
            count: logits.len(),
        }
    }
}

#[derive(Clone, Debug)]
pub struct ForwardFixture {
    /// Micro-batch 0 of step 0 of `batch_starts.json`.
    pub batch: TokenBatch,
    pub vocab: usize,
    /// `[batch, seq_len, vocab]`, from the init parameters.
    pub logits: Vec<f32>,
    /// nanolab's mean cross-entropy (`F.cross_entropy`, fp32).
    pub loss: f32,
    pub checksums: LogitsChecksums,
    pub provenance: Provenance,
}

fn ids(values: Vec<i64>, vocab: usize) -> Result<Vec<u32>, OjasError> {
    values
        .into_iter()
        .map(|v| {
            u32::try_from(v)
                .ok()
                .filter(|&u| (u as usize) < vocab)
                .ok_or_else(|| bad(&format!("token id {v} outside the vocabulary")))
        })
        .collect()
}

fn f32_exact(meta: &Meta, key: &str) -> Result<f32, OjasError> {
    let v = meta.num(key)?;
    let f = v as f32;
    if f64::from(f) != v {
        return Err(bad(&format!("metadata {key:?} = {v} is not an f32 value")));
    }
    Ok(f)
}

pub fn tiny_forward() -> Result<ForwardFixture, OjasError> {
    let st = SafeTensors::parse(FORWARD)?;
    let provenance = Provenance::of(&st)?;
    let meta = &provenance.meta;
    if provenance.kind()? != "forward" {
        return Err(bad("forward fixture kind is not forward"));
    }
    let spec = crate::spec::tiny_spec();
    let shape = |name: &str| st.entry(name).map(|e| e.shape.clone());
    let (b, t) = match shape("x").as_deref() {
        Some(&[b, t]) => (b, t),
        _ => return Err(bad("x is not [batch, seq_len]")),
    };
    if shape("y") != Some(vec![b, t]) || shape("logits") != Some(vec![b, t, spec.vocab]) {
        return Err(bad("forward tensors disagree on [batch, seq_len, vocab]"));
    }
    let batch = TokenBatch {
        x: ids(st.i64s("x")?, spec.vocab)?,
        y: ids(st.i64s("y")?, spec.vocab)?,
        batch: b,
        seq_len: t,
    };
    let loss = f32_exact(meta, "loss")?;
    if u64::from(loss.to_bits()) as f64 != meta.num("loss_f32_bits")? {
        return Err(bad("loss and loss_f32_bits disagree"));
    }
    let c = meta.object("logits_checksums")?;
    Ok(ForwardFixture {
        batch,
        vocab: spec.vocab,
        logits: st.f32s("logits")?,
        loss,
        checksums: LogitsChecksums {
            sum: c.num("sum")?,
            sum_sq: c.num("sum_sq")?,
            weighted: c.num("weighted")?,
            count: c.count("count")?,
        },
        provenance,
    })
}

// ---------------------------------------------------------------------------
// (c) gradients
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GradsAt {
    /// The init parameters (`init.safetensors`).
    Init,
    /// The f32-NS5 trace's parameters after step 5 (`trace_ns5_f32`).
    Step5,
}

#[derive(Clone, Debug)]
pub struct GradsFixture {
    pub at: GradsAt,
    /// d(loss · loss_seed)/dθ on the forward fixture's batch. Parameters
    /// without a gradient in torch (`no_grad`) are absent.
    pub grads: TensorSet,
    pub loss: f32,
    /// 1/K: nanolab divides each micro-loss by `grad_accum` before backward.
    pub loss_seed: f32,
    pub no_grad: Vec<String>,
    /// Gradients that are exactly zero everywhere.
    pub zero_grad: Vec<String>,
    pub provenance: Provenance,
}

pub fn tiny_grads(at: GradsAt) -> Result<GradsFixture, OjasError> {
    let bytes = match at {
        GradsAt::Init => GRADS_INIT,
        GradsAt::Step5 => GRADS_STEP5,
    };
    let st = SafeTensors::parse(bytes)?;
    let provenance = Provenance::of(&st)?;
    let meta = &provenance.meta;
    if provenance.kind()? != "grads" {
        return Err(bad("grads fixture kind is not grads"));
    }
    let want_at = match at {
        GradsAt::Init => "init",
        GradsAt::Step5 => "trace_ns5_f32 after step 5",
    };
    if meta.str("params")? != want_at {
        return Err(bad("grads fixture names other parameters"));
    }
    let grads = f32_set(&st)?;
    let no_grad = meta.strings("no_grad")?;
    let zero_grad = meta.strings("zero_grad")?;
    let rows = expected_params(&crate::spec::tiny_spec());
    for row in &rows {
        let present = grads.get(&row.name);
        let listed = no_grad.contains(&row.name);
        match (present, listed) {
            (Some(g), false) if g.shape == row.shape => {}
            (None, true) => {}
            _ => {
                return Err(bad(&format!(
                    "{}: gradient presence or shape disagrees with no_grad",
                    row.name
                )))
            }
        }
    }
    if grads.len() + no_grad.len() != rows.len() {
        return Err(bad("grads fixture holds tensors outside §2"));
    }
    for g in grads.iter() {
        let all_zero = g.data.iter().all(|&v| v == 0.0);
        if all_zero != zero_grad.contains(&g.name) {
            return Err(bad(&format!("{}: zero_grad list is wrong", g.name)));
        }
    }
    Ok(GradsFixture {
        at,
        grads,
        loss: f32_exact(meta, "loss")?,
        loss_seed: f32_exact(meta, "loss_seed")?,
        no_grad,
        zero_grad,
        provenance,
    })
}

// ---------------------------------------------------------------------------
// (d) training traces
// ---------------------------------------------------------------------------

/// Precision of Muon's Newton-Schulz iteration in the torch run.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Ns5 {
    /// nanolab patched to iterate in f32 (ojas's Muon; pytorch-parity-plan F8).
    F32,
    /// Stock nanolab: bf16 iteration.
    Bf16,
}

/// The training configuration a trace ran, from its nanolab `Config`.
#[derive(Clone, Debug, PartialEq)]
pub struct TrainSetup {
    pub seed: u64,
    pub batch: usize,
    pub accum: usize,
    pub seq_len: usize,
    pub optimizer: String,
    pub schedule: String,
    pub warmup_steps: usize,
    /// `lr_max_steps` if set, else `max_steps` (schedules.py:51).
    pub total_steps: usize,
    pub lr_floor_frac: f64,
    pub wsd_decay_frac: f64,
    /// AdamW peak LR (embedding and vector groups).
    pub lr: f64,
    /// Muon peak LR (2-D hidden weights).
    pub matrix_lr: f64,
    pub muon_momentum: f64,
    pub weight_decay: f64,
    pub beta1: f64,
    pub beta2: f64,
    pub eps: f64,
    pub grad_clip: f64,
    /// `fixtures/tiny/tokens.bin`; batches come from ojas-data's
    /// `BatchSampler` with `seed`, `batch` and `seq_len`, `accum` per step.
    pub token_bin: PathBuf,
}

fn train_setup(cfg: &Meta) -> Result<TrainSetup, OjasError> {
    let lr_max = cfg.count("lr_max_steps")?;
    Ok(TrainSetup {
        seed: cfg.count("seed")? as u64,
        batch: cfg.count("batch_size")?,
        accum: cfg.count("grad_accum")?,
        seq_len: cfg.count("block_size")?,
        optimizer: cfg.str("optimizer")?.to_string(),
        schedule: cfg.str("schedule")?.to_string(),
        warmup_steps: cfg.count("warmup_steps")?,
        total_steps: if lr_max > 0 {
            lr_max
        } else {
            cfg.count("max_steps")?
        },
        lr_floor_frac: cfg.num("lr_floor_frac")?,
        wsd_decay_frac: cfg.num("wsd_decay_frac")?,
        lr: cfg.num("lr")?,
        matrix_lr: cfg.num("matrix_lr")?,
        muon_momentum: cfg.num("muon_momentum")?,
        weight_decay: cfg.num("weight_decay")?,
        beta1: cfg.num("beta1")?,
        beta2: cfg.num("beta2")?,
        eps: cfg.num("eps")?,
        grad_clip: cfg.num("grad_clip")?,
        token_bin: PathBuf::from(TINY_DIR).join("tokens.bin"),
    })
}

#[derive(Clone, Debug)]
pub struct TraceFixture {
    pub ns5: Ns5,
    /// Steps recorded (40).
    pub steps: usize,
    /// `params` are the parameters after this many steps (5).
    pub params_after_step: usize,
    /// Per step: the schedule multiplier (apply_lr's `lr / peak`).
    pub lr_mult: Vec<f64>,
    /// Per step and micro-batch, `steps * accum`: unscaled micro-batch losses.
    pub micro_loss: Vec<f64>,
    /// Per step: mean micro-batch loss (what ojas's trainer reports).
    pub mean_loss: Vec<f64>,
    /// Per step: what nanolab's train.py:348 logs, the LAST micro-batch loss
    /// (scaled by 1/K, then times K), not the mean.
    pub nanolab_loss: Vec<f64>,
    /// Per step: the global grad norm before clipping.
    pub grad_norm: Vec<f64>,
    pub params: TensorSet,
    pub train: TrainSetup,
    pub provenance: Provenance,
}

pub fn tiny_trace(ns5: Ns5) -> Result<TraceFixture, OjasError> {
    let (bytes, tag) = match ns5 {
        Ns5::F32 => (TRACE_F32, "f32"),
        Ns5::Bf16 => (TRACE_BF16, "bf16"),
    };
    let st = SafeTensors::parse(bytes)?;
    let provenance = Provenance::of(&st)?;
    let meta = &provenance.meta;
    if provenance.kind()? != "trace" || meta.str("ns5")? != tag {
        return Err(bad("trace fixture kind or ns5 disagrees with its file"));
    }
    let train = train_setup(&provenance.config()?)?;
    let steps = meta.count("steps")?;
    let params_after_step = meta.count("params_after_step")?;
    let per_step = |key: &str, n: usize| -> Result<Vec<f64>, OjasError> {
        let v = meta.numbers(key)?;
        if v.len() != n || v.iter().any(|x| !x.is_finite()) {
            return Err(bad(&format!(
                "trace {key} has {} finite values, need {n}",
                v.len()
            )));
        }
        Ok(v)
    };
    let params = f32_set(&st)?;
    check_names_and_shapes(&params, &crate::spec::tiny_spec())?;
    if params_after_step == 0 || params_after_step > steps {
        return Err(bad("params_after_step outside the trace"));
    }
    Ok(TraceFixture {
        ns5,
        steps,
        params_after_step,
        lr_mult: per_step("lr_mult", steps)?,
        micro_loss: per_step("micro_loss", steps * train.accum)?,
        mean_loss: per_step("mean_loss", steps)?,
        nanolab_loss: per_step("nanolab_loss", steps)?,
        grad_norm: per_step("grad_norm", steps)?,
        params,
        train,
        provenance,
    })
}

// ---------------------------------------------------------------------------
// (e) LR schedules
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, PartialEq)]
pub struct LrCase {
    pub name: String,
    pub schedule: String,
    pub warmup_steps: usize,
    pub total_steps: usize,
    pub lr_floor_frac: f64,
    pub wsd_decay_frac: f64,
    pub peak: f64,
    /// `schedule(step) / peak` for steps `0..multipliers.len()`.
    pub multipliers: Vec<f64>,
}

#[derive(Clone, Debug)]
pub struct LrSchedules {
    pub cases: Vec<LrCase>,
    pub provenance: Provenance,
}

pub const LR_CASES: [&str; 4] = [
    "tiny_cosine",
    "tiny_wsd",
    "acceptance_cosine",
    "acceptance_wsd",
];

pub fn lr_schedules() -> Result<LrSchedules, OjasError> {
    let meta = Meta::parse(LR_SCHEDULES)?;
    if meta.str("op")? != "lr_schedule" {
        return Err(bad("lr_schedules.json op is not lr_schedule"));
    }
    let steps = meta.count("steps")?;
    let mut cases = Vec::new();
    for name in LR_CASES {
        let c = meta.object(name)?;
        let multipliers = c.numbers("multipliers")?;
        if multipliers.len() != steps {
            return Err(bad(&format!(
                "{name}: {} multipliers, need {steps}",
                multipliers.len()
            )));
        }
        cases.push(LrCase {
            name: name.to_string(),
            schedule: c.str("schedule")?.to_string(),
            warmup_steps: c.count("warmup_steps")?,
            total_steps: c.count("total_steps")?,
            lr_floor_frac: c.num("lr_floor_frac")?,
            wsd_decay_frac: c.num("wsd_decay_frac")?,
            peak: c.num("peak")?,
            multipliers,
        });
    }
    Ok(LrSchedules {
        cases,
        provenance: Provenance::from_meta(meta)?,
    })
}

// ---------------------------------------------------------------------------
// batch-start handoff
// ---------------------------------------------------------------------------

/// `batch_starts.json` (`ojas-batch-starts-v1`, examples/dump_batch_starts.rs).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BatchStarts {
    pub seed: u64,
    pub seq_len: usize,
    pub batch: usize,
    pub accum: usize,
    pub steps: usize,
    pub bin_header_bytes: usize,
    pub bin_tokens: usize,
    pub bin_fnv1a64: u64,
    pub windows_per_epoch: usize,
    /// (epoch, window ordinal) after the last micro-batch.
    pub cursor_after: (u64, u64),
    /// `steps * accum * batch` token offsets, ordered (step, micro, row).
    pub starts: Vec<u64>,
    /// The `seq_len + 1` tokens of every window, in the same order, as
    /// ojas-data's `TokenBin` read them.
    pub rows: Option<Vec<u16>>,
}

impl BatchStarts {
    /// Starts of micro-batch `micro` of `step`.
    pub fn micro_starts(&self, step: usize, micro: usize) -> Result<&[u64], OjasError> {
        if step >= self.steps || micro >= self.accum {
            return Err(bad("step or micro-batch outside the dump"));
        }
        let first = (step * self.accum + micro) * self.batch;
        Ok(&self.starts[first..first + self.batch])
    }

    /// The micro-batch read from `tokens` (a headerless bin's ids), the way
    /// `python/batches.py` replays it.
    pub fn micro_batch(
        &self,
        tokens: &[u16],
        step: usize,
        micro: usize,
    ) -> Result<TokenBatch, OjasError> {
        let t = self.seq_len;
        let mut x = Vec::with_capacity(self.batch * t);
        let mut y = Vec::with_capacity(self.batch * t);
        for &start in self.micro_starts(step, micro)? {
            let s = usize::try_from(start).map_err(|_| bad("start exceeds usize"))?;
            let row = tokens
                .get(s..s + t + 1)
                .ok_or_else(|| bad("window runs past the token bin"))?;
            x.extend(row[..t].iter().map(|&v| u32::from(v)));
            y.extend(row[1..].iter().map(|&v| u32::from(v)));
        }
        Ok(TokenBatch {
            x,
            y,
            batch: self.batch,
            seq_len: t,
        })
    }
}

pub fn parse_batch_starts(text: &str) -> Result<BatchStarts, OjasError> {
    let meta = Meta::parse(text)?;
    if meta.str("format")? != "ojas-batch-starts-v1" {
        return Err(bad("batch starts format is not ojas-batch-starts-v1"));
    }
    if meta.str("sampler")? != "ojas_data::BatchSampler" {
        return Err(bad(
            "batch starts were not drawn by ojas_data::BatchSampler",
        ));
    }
    let hash = meta.str("bin_fnv1a64")?;
    let bin_fnv1a64 = (hash.len() == 16)
        .then(|| u64::from_str_radix(hash, 16).ok())
        .flatten()
        .ok_or_else(|| bad("bin_fnv1a64 is not 16 hex digits"))?;
    let starts = meta.counts("starts")?;
    let cursor = meta.counts("cursor_after")?;
    let [epoch, ordinal] = cursor[..] else {
        return Err(bad("cursor_after is not [epoch, ordinal]"));
    };
    let doc = BatchStarts {
        seed: meta.count("seed")? as u64,
        seq_len: meta.count("seq_len")?,
        batch: meta.count("batch")?,
        accum: meta.count("accum")?,
        steps: meta.count("steps")?,
        bin_header_bytes: meta.count("bin_header_bytes")?,
        bin_tokens: meta.count("bin_tokens")?,
        bin_fnv1a64,
        windows_per_epoch: meta.count("windows_per_epoch")?,
        cursor_after: (epoch, ordinal),
        starts,
        rows: None,
    };
    let n = doc
        .steps
        .checked_mul(doc.accum)
        .and_then(|v| v.checked_mul(doc.batch))
        .ok_or_else(|| bad("steps * accum * batch overflows"))?;
    if doc.starts.len() != n {
        return Err(bad(&format!("{} starts, need {n}", doc.starts.len())));
    }
    let rows = if meta.has("rows") {
        let rows: Vec<u16> = meta
            .counts("rows")?
            .into_iter()
            .map(|v| u16::try_from(v).map_err(|_| bad("row token exceeds u16")))
            .collect::<Result<_, _>>()?;
        if rows.len() != n * (doc.seq_len + 1) {
            return Err(bad("rows length disagrees with starts"));
        }
        Some(rows)
    } else {
        None
    };
    Ok(BatchStarts { rows, ..doc })
}

pub fn tiny_batch_starts() -> Result<BatchStarts, OjasError> {
    parse_batch_starts(BATCH_STARTS)
}

/// `tokens.bin` as ids (headerless little-endian u16).
pub fn tiny_tokens() -> Result<Vec<u16>, OjasError> {
    let (pairs, rest) = TOKENS.as_chunks::<2>();
    if !rest.is_empty() {
        return Err(bad("tokens.bin has an odd byte length"));
    }
    Ok(pairs.iter().map(|c| u16::from_le_bytes(*c)).collect())
}

/// The raw bytes of `tokens.bin`.
pub fn tiny_token_bytes() -> &'static [u8] {
    TOKENS
}

/// FNV-1a 64, as examples/dump_batch_starts.rs and python/batches.py compute it.
pub fn fnv1a64(bytes: &[u8]) -> u64 {
    bytes.iter().fold(0xcbf2_9ce4_8422_2325, |h, &b| {
        (h ^ u64::from(b)).wrapping_mul(0x0000_0100_0000_01b3)
    })
}
